spring.application.name=electronic
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/electronic_db
spring.datasource.username=root
spring.datasource.password=z_verseau@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.id.uuid_generator_strategy=org.hibernate.id.uuid.StandardRandomStrategy
spring.jpa.properties.hibernate.jdbc.use_streams_for_binary=false
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=VARCHAR

# Pour servir les fichiers statiques
spring.web.resources.static-locations=file:uploads/produits/,classpath:/static/
spring.mvc.static-path-pattern=/api/v1/produits/uploads/produits/**

app.secret-key= maSuperCleSecretePourJwtToken12345678901234567890
app.expirationTime= 86400000


#hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.main.banner-mode = off

