spring.application.name=electronic
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.id.uuid_generator_strategy=org.hibernate.id.uuid.StandardRandomStrategy
spring.jpa.properties.hibernate.jdbc.use_streams_for_binary=false
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=VARCHAR

spring.web.resources.static-locations=file:uploads/produits/,classpath:/static/
spring.mvc.static-path-pattern=/api/v1/produits/uploads/produits/**

app.secret-key=${APP_SECRET_KEY}
app.expirationTime=${APP_EXPIRATION_TIME}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect